package cli

import (
	"strings"

	"github.com/spf13/cobra"
)

func init() {
	// Usage lines are generated by cobra with a literal " [flags]" suffix.
	cobra.AddTemplateFunc("servitorRunes", func(s string) string { return strings.Replace(s, "[flags]", "[runes]", 1) })
}

// flavor speaks the liturgy through cobra's built-in texts and hides the
// help ritual and runes, which still work but are never offered.
func flavor(root *cobra.Command) {
	root.SetUsageTemplate(flavorUsage(root.UsageTemplate()))
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	root.InitDefaultVersionFlag()
	if f := root.Flags().Lookup("version"); f != nil {
		f.Usage = "reveal the pattern of this servitor"
	}
	for _, c := range root.Commands() {
		switch c.Name() {
		case "help":
			c.Short = "Recite the codex"
			c.Hidden = true
		case "completion":
			c.Short = "Engrave completion litanies into your terminal"
			for _, sub := range c.Commands() {
				sub.Short = "Engrave the completion litany for " + sub.Name()
				_ = sub.Flags().MarkHidden("no-descriptions") // its name is no word of the liturgy
			}
		}
	}
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		c.InitDefaultHelpFlag()
		if f := c.Flags().Lookup("help"); f != nil {
			f.Usage = "reveal the lore of " + c.Name()
			f.Hidden = true
		}
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(root)
}

// flavorUsage rewrites cobra's usage template headings into liturgy and
// stops it from naming the help ritual in listings.
func flavorUsage(tmpl string) string {
	return strings.NewReplacer(
		`(or .IsAvailableCommand (eq .Name "help"))`, ".IsAvailableCommand",
		"{{.UseLine}}", "{{servitorRunes .UseLine}}",
		`Use "{{.CommandPath}} [command] --help" for more information about a command.`,
		`Recite "servitor expound <topic>" for the lore of every ritual, rune, step and key.`,
		"Usage:", "Invocation:",
		"Aliases:", "Also Known As:",
		"Examples:", "Exempla:",
		"Available Commands:", "Sanctioned Rituals:",
		"Additional Commands:", "Lesser Rituals:",
		"Global Flags:", "Universal Runes:",
		"Flags:", "Runes:",
		"Additional help topics:", "Further Lore:",
		"[command]", "[ritual]",
	).Replace(tmpl)
}
