package cli

import (
	"strings"

	"github.com/spf13/cobra"
)

// exampleRite is the sample definition shown in the root help.
const exampleRite = `  {
    "description": "Hide the mouse cursor after inactivity",
    "states": ["on", "off"],
    "files": [{
      "file": "~/.config/niri/util.kdl",
      "guard": "mouse-autohide",          // default: the name
      "comment": "//",                    // default: inferred from extension
      "values": [
        {"state": "on",  "value": "cursor {\n    hide-after-inactive-ms 400\n}"},
        {"state": "off", "value": ""}
      ],
      "meta": {"reason": {"optional": true, "description": "why it was switched"}}
    }]
  }`

const rootLong = `+++ SERVITOR · Configuration Thrall of the Adeptus Mechanicus +++

The servitor performs RITES upon the sacred texts of your machine. Each rite
knows a fixed set of ASPECTS. Invoking an aspect rewrites one warded SANCTUM in
every VESSEL of the rite:

  // begin servitor managed -- <ward> -- state|on reason|"gaming remnant"
  <scripture kept by the servitor>
  // end servitor managed -- <ward>

Only the lines between the wards are ever touched; the rest of the vessel
remains inviolate. A sanctum not yet consecrated is appended to the end of its
vessel. The header bears INSCRIPTIONS as key|value pairs: "state" is inscribed
by the servitor alone, all others are declared by the rite and may be
overridden with --<key> runes.

Rites are kept in the Librarium (--librarium, or ` + EnvLibrarium + `), one per scripture:
  <Librarium>/rites/<name>.json      (JSON with comments; "switches/" is also searched)

` + exampleRite + `

Invoked without a ritual (and attached to a terminal), the servitor awakens
the COGITATOR, an interactive shrine for performing, consecrating, amending and
excommunicating rites.`

const rootExample = `  servitor                                   # awaken the cogitator
  servitor invoke mouse-autohide-toggle on --reason "gaming remnant"
  servitor invoke mouse-autohide-toggle off
  servitor augury mouse-autohide-toggle
  servitor augury mouse-autohide-toggle state
  servitor augury mouse-autohide-toggle --is on && echo "the cursor is veiled"
  servitor inquisition
  source <(servitor completion bash)`

const switchLongHelp = `Invoke an aspect of a rite: every sanctum of the rite is rewritten with the
scripture its aspect prescribes.

Every inscription declared by the rite is available as a --<key> rune that
overrides the prescribed value; pass an empty string to erase it. Consult
"servitor invoke <rite> --help" to learn the aspects and runes of one rite.`

const metaLongHelp = `Perform an augury: read the inscriptions from the sanctum headers of a rite.

Without a key, the augury speaks a JSON object with "state" and every inscribed
value. With a key, it speaks only that value (an empty line when uninscribed).
With --is <aspect>, it speaks nothing and exits 0 when the rite stands in that
aspect and 1 otherwise, for shell conditions.

Exit codes: 0 the augury succeeded, 1 --is did not match, 2 the augury failed
(unknown rite, never performed, or vessels that disagree; consult --per-file).`

const verifyLongHelp = `Summon the Inquisition to examine every rite (or only the named ones). Each
heresy is reported with its location as file:line:column.

The Inquisition purges: malformed JSON, unknown or mistyped fields, undeclared
or missing aspects, undeclared or reserved inscriptions, rites whose names
clash (one name recorded in several files), wards claimed twice for the same
vessel, and — unless --spare-vessels — vessels that are missing, sanctums with
broken or duplicated wards, and scripture tainted by unsanctioned hands.

Exits 1 when any heresy was found. Impurities are noted but forgiven.`

func init() {
	// Usage lines are generated by cobra with a literal " [flags]" suffix.
	cobra.AddTemplateFunc("servitorRunes", func(s string) string { return strings.Replace(s, "[flags]", "[runes]", 1) })
}

// flavor speaks the liturgy through cobra's built-in texts and hides the
// help ritual and runes, which still work but are never offered.
func flavor(root *cobra.Command) {
	root.SetUsageTemplate(flavorUsage(root.UsageTemplate()))
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	root.InitDefaultVersionFlag()
	if f := root.Flags().Lookup("version"); f != nil {
		f.Usage = "reveal the pattern of this servitor"
	}
	for _, c := range root.Commands() {
		switch c.Name() {
		case "help":
			c.Short = "Consult the lore of any ritual"
			c.Hidden = true
		case "completion":
			c.Short = "Engrave completion litanies into your shell"
			for _, sub := range c.Commands() {
				sub.Short = "Engrave the completion litany for " + sub.Name()
			}
		}
	}
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		c.InitDefaultHelpFlag()
		if f := c.Flags().Lookup("help"); f != nil {
			f.Usage = "reveal the lore of " + c.Name()
			f.Hidden = true
		}
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(root)
}

// flavorUsage rewrites cobra's usage template headings into liturgy and
// stops it from naming the help ritual in listings.
func flavorUsage(tmpl string) string {
	return strings.NewReplacer(
		`(or .IsAvailableCommand (eq .Name "help"))`, ".IsAvailableCommand",
		"{{.UseLine}}", "{{servitorRunes .UseLine}}",
		`Use "{{.CommandPath}}`, `Consult "{{.CommandPath}}`,
		"Usage:", "Invocation:",
		"Aliases:", "Also Known As:",
		"Examples:", "Exempla:",
		"Available Commands:", "Sanctioned Rituals:",
		"Additional Commands:", "Lesser Rituals:",
		"Global Flags:", "Universal Runes:",
		"Flags:", "Runes:",
		"Additional help topics:", "Further Lore:",
		"for more information about a command.", "for deeper lore on a ritual.",
		"[command]", "[ritual]",
	).Replace(tmpl)
}
