package cli

import (
	"strings"

	"github.com/spf13/cobra"

	"github.com/nerdwave-nick/servitor/internal/librarium"
)

// exampleRite is the sample scripture shown in the root help.
const exampleRite = `  {
    "pattern": "Mark I",
    "purpose": "Hide the mouse cursor after inactivity",
    "aspects": ["on", "off"],
    "inscriptions": {"reason": {"purpose": "why the rite was invoked"}},
    "liturgy": [
      {"sanctum": "~/.config/niri/util.kdl",   // ward: the rite's name; glyph: by the vessel
       "scripture": {"on": "cursor {\n    hide-after-inactive-ms 400\n}", "off": ""}},
      {"incantation": "niri msg action load-config-file"},
      {"vox-cast": "success"}
    ]
  }`

const rootLong = `+++ SERVITOR · Thrall of the Adeptus Mechanicus +++

The servitor performs RITES upon your machine. Each rite knows a fixed set of
ASPECTS and a LITURGY of steps, performed in the order written: SANCTUMS,
TRANSCRIPTIONS, TETHERS, INCANTATIONS, LITANIES and VOX-CASTS. Should a step
fall, every deed already done is reverted.

A sanctum rewrites only its warded region of a VESSEL; the rest of the vessel
remains inviolate, and a sanctum not yet kept is appended to its end:

  // +++ begin of sanctum <ward> -- aspect|on +++
  <scripture kept by the servitor>
  // +++ end of sanctum <ward> +++

INSCRIPTIONS declared by a rite are given as --<key> runes, or decreed by the
rite for each aspect; the servitor keeps them on the rite's data-slate.

Rites are kept in the Librarium (--librarium, or ` + EnvLibrarium + `), one scripture
each, beside the settings in servitor.json:
  <Librarium>/rites/<name>.json      (JSON with comments, of pattern Mark I)

` + exampleRite + `

Every invocation is recorded in the chronicle (--chronicle, or ` + librarium.EnvChronicle + `).

Invoked without a ritual (and attached to a terminal), the servitor awakens
the COGITATOR, an interactive shrine for performing, consecrating, amending and
excommunicating rites.`

const rootExample = `  servitor                                   # awaken the cogitator
  servitor invoke mouse-autohide-toggle on --reason "gaming remnant"
  servitor invoke mouse-autohide-toggle off --foresee
  servitor augury mouse-autohide-toggle
  servitor augury mouse-autohide-toggle aspect
  servitor augury mouse-autohide-toggle --is on && echo "the cursor is veiled"
  servitor census
  servitor inquisition
  source <(servitor completion bash)`

const invokeLongHelp = `Invoke an aspect of a rite: its pre-flight examines every step, then its
liturgy is performed step by step in the order written. Should a step fall —
or should the invocation be halted by an interrupt — every deed already done is
reverted, and the lament tells what fell and how the reversion went. Vox-casts
are printed on the terminal, or sent to the desktop when there is none.

Every inscription declared by the rite is a --<key> rune that outranks the
rite's decree; pass an empty word to clear it. Consult
"servitor invoke <rite> --help" to learn the aspects and runes of one rite.`

const auguryLongHelp = `Perform an augury: read which aspect a rite stands in, how it stands, its
inscriptions, its last rite and every omen.

Without a key, the augury speaks one JSON object. With a key — aspect,
standing, desecrated, former or an inscription of the rite — it speaks only
that value (an empty line when uninscribed). With --is <aspect>, it speaks
nothing and exits 0 when the rite stands in that aspect and 1 otherwise, for
shell conditions.

Exit codes: 0 the augury succeeded, 1 --is did not match, 2 the augury could
not be read (unknown rite or key, an aspect the rite knows not, a heretical
rite asked --is).`

const censusLongHelp = `Take a census of every rite of the Librarium: the aspect it stands in, how it
stands (performed, dormant, corrupted, tainted, desecrated or heretical), its
aspects, its last rite and its purpose. In binharic every rite bears rite,
aspect, standing, aspects, purpose, desecrated, last_rite and recorded_in.`

const inquisitionLongHelp = `Summon the Inquisition to examine every rite (or only the named ones), the
settings and the machine their liturgies act upon. Each heresy and impurity is
reported with its place as file:line:column.

Heresies must be purged: malformed scripture, unknown keys, a missing or
foreign pattern, aspects empty or unworthy, unknown placeholders and
undeclared inscriptions, missing tomes, wards claimed twice in one vessel,
rites recorded twice, heretical settings, and sanctums whose markers are
broken. Impurities are noted but forgiven: tongues spoken nowhere, vessels
missing without consecrate, anchors missing for some aspect, mandatory
inscriptions without decree, success vox-casts that are not last, tainted
sanctums and desecrated rites. --spare-vessels judges the scriptures alone.

Exits 1 when any heresy was found.`

func init() {
	// Usage lines are generated by cobra with a literal " [flags]" suffix.
	cobra.AddTemplateFunc("servitorRunes", func(s string) string { return strings.Replace(s, "[flags]", "[runes]", 1) })
}

// flavor speaks the liturgy through cobra's built-in texts and hides the
// help ritual and runes, which still work but are never offered.
func flavor(root *cobra.Command) {
	root.SetUsageTemplate(flavorUsage(root.UsageTemplate()))
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	root.InitDefaultVersionFlag()
	if f := root.Flags().Lookup("version"); f != nil {
		f.Usage = "reveal the pattern of this servitor"
	}
	for _, c := range root.Commands() {
		switch c.Name() {
		case "help":
			c.Short = "Consult the lore of any ritual"
			c.Hidden = true
		case "completion":
			c.Short = "Engrave completion litanies into your shell"
			for _, sub := range c.Commands() {
				sub.Short = "Engrave the completion litany for " + sub.Name()
			}
		}
	}
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		c.InitDefaultHelpFlag()
		if f := c.Flags().Lookup("help"); f != nil {
			f.Usage = "reveal the lore of " + c.Name()
			f.Hidden = true
		}
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(root)
}

// flavorUsage rewrites cobra's usage template headings into liturgy and
// stops it from naming the help ritual in listings.
func flavorUsage(tmpl string) string {
	return strings.NewReplacer(
		`(or .IsAvailableCommand (eq .Name "help"))`, ".IsAvailableCommand",
		"{{.UseLine}}", "{{servitorRunes .UseLine}}",
		`Use "{{.CommandPath}}`, `Consult "{{.CommandPath}}`,
		"Usage:", "Invocation:",
		"Aliases:", "Also Known As:",
		"Examples:", "Exempla:",
		"Available Commands:", "Sanctioned Rituals:",
		"Additional Commands:", "Lesser Rituals:",
		"Global Flags:", "Universal Runes:",
		"Flags:", "Runes:",
		"Additional help topics:", "Further Lore:",
		"for more information about a command.", "for deeper lore on a ritual.",
		"[command]", "[ritual]",
	).Replace(tmpl)
}
